### ISSUE TITLE
boot sequence never lands on NVME

### ISSUE THREAD

**Issue by dmorn** [nix-community/hardware-mnt-reform#5]
I am stuck (as I do not get it) at step
```
* Move /mnt/boot to /mnt/boot.bak. Uboot will now boot from /mnt/extlinux.
```
Now, /mnt/boot still has the SD partition mounted on it of the "live" image, while /mnt has the nvme drive with nixos installed on it. If I try running
```
mv /mnt/boot /mnt/boot.bak
```
I get that the resource is busy so I cannot complete the operation. I don't get what I am supposed to do and what I am trying to achieve with this operation.

Furthermore extlinux is not present in /mnt after the installation process, I don't know whether this is expected or not.

Any help would be appreciated, thanks!

**Comment by jollheef** [comment]
I don't use an SD card for the boot process, but It seems there is an error, and it should be `mv /boot /boot.bak`.

**Comment by dmorn** [comment]
Hi @jollheef thanks for joining. This is what I would eventually like to achieve as well, did you keep the rescue system on emmc?

**Comment by jollheef** [comment]
I use /dev/mmcblk0p1 as /boot and U-Boot is flashed to /dev/mmcblk0boot0.

Here is the complete installation process: https://dumpstack.io/1650956090_nixos_on_mnt_reform.html

**Comment by dmorn** [comment]
This one includes many steps that are not listed in the README. Among other notable things I partitioned nvme with MBR, not GPT. I'll let you know how this goes, thanks!

**Comment by dmorn** [comment]
Hey @jollheef thanks for your guide, it worked indeed! I think the readme here should me merged with the link you provided. For a noob like me that was invaluable and the actual guidance I was looking for. There is still a little thing that is not working as expected though. I do not get the grub menu that lets you choose which nix generation you want to boot.

In my `configuration.nix` I have `boot.loader.grub.enable = false` which was automatically set by the `generate-config` command. How did you configure it? It is just `s/false/true` distant? 😄

**Comment by dmorn** [comment]
Uh i see now in the notes that you can choose the generation with uart only. Does it mean I need another machine to achieve that? Why?

**Comment by jollheef** [comment]
I just haven't played with grub on MNT reform yet, so I don't have a complete solution.

You can still change the generation after boot (see [wiki page](https://nixos.wiki/wiki/NixOS#Generations)). However, in case of issues, UART is the only way without grub.

Edit: U-Boot actually supposed to have a boot menu, but it seems like there is no support for MNT Reform yet.

**Comment by dmorn** [comment]
Thanks for your help @jollheef! I'll play with the boot process after setting up an UART connection to another machine, let's see how it goes :D
